# Generated by Django 2.1.8 on 2019-05-20 13:40

import aldryn_categories.fields
import aldryn_newsblog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_newsblog', '0016_auto_20180329_1417'),
        ('aldryn_categories', '0004_auto_20150623_0859'),
        ('cms', '0022_auto_20180620_1551'),
        ('aldryn_newsblog_extra_plugins', '0003_auto_20170924_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlogLatestArticlesByCategoryPlugin',
            fields=[
                ('cache_duration', models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached.")),
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('style', models.CharField(choices=[('list', 'Standard')], default='list', max_length=50, verbose_name='Style')),
                ('article_count', models.IntegerField(default=5, help_text='The maximum number of latest articles to display.', verbose_name='count')),
                ('app_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aldryn_newsblog.NewsBlogConfig', verbose_name='Apphook configuration')),
                ('category', aldryn_categories.fields.CategoryForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aldryn_categories.Category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
            bases=(aldryn_newsblog.models.PluginEditModeMixin, 'cms.cmsplugin', models.Model),
        ),
    ]
