# Generated by Django 2.1.8 on 2019-05-20 14:11

import aldryn_categories.fields
import aldryn_newsblog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('aldryn_categories', '0004_auto_20150623_0859'),
        ('aldryn_newsblog_extra_plugins', '0004_newsbloglatestarticlesbycategoryplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsBlogCategoryRelatedPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_newsblog_extra_plugins_newsblogcategoryrelatedplugin', serialize=False, to='cms.CMSPlugin')),
                ('cache_duration', models.PositiveSmallIntegerField(default=0, help_text="The maximum duration (in seconds) that this plugin's content should be cached.")),
                ('style', models.CharField(choices=[('list', 'Standard')], default='list', max_length=50, verbose_name='Style')),
                ('article_count', models.PositiveIntegerField(default=10, help_text='The maximum number of related articles to display (0 for all).')),
                ('exclude_categories', aldryn_categories.fields.CategoryManyToManyField(blank=True, to='aldryn_categories.Category', verbose_name='excluded categories')),
            ],
            options={
                'abstract': False,
            },
            bases=(aldryn_newsblog.models.PluginEditModeMixin, 'cms.cmsplugin', models.Model),
        ),
        migrations.AlterField(
            model_name='newsbloglatestarticlesbycategoryplugin',
            name='article_count',
            field=models.IntegerField(default=10, help_text='The maximum number of latest articles to display.', verbose_name='count'),
        ),
        migrations.AlterField(
            model_name='newsblogtagrelatedplugin',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='aldryn_newsblog_extra_plugins_newsblogtagrelatedplugin', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
